import test from 'node:test';
import assert from 'node:assert/strict';
import { Session } from '@deepseek-ai/dsh-session';
import { isCompactCheckpointSource, toolPairingBalancedBefore, toolPairingBalancedAfter } from '@deepseek-ai/dsh-compaction';
import { createAssistantMessage, createToolResultMessage } from '@deepseek-ai/dsh-llm';
import { StructuredCodexCompactionEngine } from '../src/structured-engine.js';
import { assertCompactionBoundaries, sanitizeCompactHistory } from '../src/compact-history.js';
import { engineFixture, user } from './helpers/engine.js';

test('legacy structured object is read-only and does not register a compaction writer', () => {
  const readCheckpoint = message => message.source.nativeCodex;
  const reader = new StructuredCodexCompactionEngine({}, { readCheckpoint, validateCheckpoint: x => x, estimateCheckpoint: () => ({ tokens: 1, exact: false, basis: 'fixture' }) });
  assert.deepEqual(reader.readCheckpoint({ source: { nativeCodex: { version: 1 } } }), { version: 1 });
  for (const key of ['compactNow', 'compactRegion', 'compactIfNeeded', 'measureEffective']) assert.equal(reader[key], undefined);
});
test('real inherited Basic transaction persists native summary, V4 replace and no fake usage', async t => {
  const f = await engineFixture(t); f.enable();
  const first = f.session.append('user/message', user('old work '.repeat(5000)), { surfaceOp: 'append' });
  const second = f.session.append('user/message', user('second work '.repeat(5000)), { surfaceOp: 'append' });
  f.session.append('user/message', user('retained tail'), { surfaceOp: 'append' });
  f.session.append('turn/start', { turn: 1 });
  const result = await f.engine.compactRegion(first.seq, second.seq, f.agent, new AbortController().signal);
  assert.ok(result);
  const events = f.session.snapshotEvents();
  const summary = events.findLast(e => e.type === 'compaction/summary');
  assert.equal(summary.data.usage, undefined);
  const replacement = events.findLast(e => e.type === 'user/message');
  assert.deepEqual(replacement.surfaceOp, { op: 'replace', startSeq: first.seq, endSeq: second.seq });
  assert.equal(isCompactCheckpointSource(replacement.data.source), true);
  assert.equal(f.ctx.codexBridge.readCheckpoint(replacement.data).version, 1);
  const restored = Session.create(f.session.id, events, f.session.header);
  assert.equal(restored.deriveMessages().length, 2);
  assert.equal(f.ctx.codexBridge.readCheckpoint(restored.deriveMessages()[0]).version, 1);
});
test('V4 tool-role pairing boundaries come from official before/after functions', () => {
  const s = Session.create('pairing');
  s.append('turn/start', { turn: 1 });
  s.append('step/start', { turn: 1, step: 1 });
  const assistant = createAssistantMessage({ source: { provider: 'openai-codex', model: 'gpt-5.4' }, content: [{ type: 'tool-call', id: 'call', name: 'read', arguments: '{}' }] });
  const a = s.append('assistant/message', { turn: 1, step: 1, message: assistant }, { surfaceOp: 'append' });
  const tool = createToolResultMessage({ callId: 'call', content: [{ type: 'text', text: 'result' }], isError: true });
  const b = s.append('tool/result', { turn: 1, step: 1, message: tool }, { surfaceOp: 'append' });
  assert.equal(tool.role, 'tool'); assert.equal(tool.toolCallId, 'call'); assert.equal(tool.isError, true);
  assert.equal(toolPairingBalancedBefore(s, a.seq), true);
  assert.equal(toolPairingBalancedAfter(s, a.seq), false);
  assert.equal(toolPairingBalancedBefore(s, b.seq), false);
  assert.equal(toolPairingBalancedAfter(s, b.seq), true);
  assertCompactionBoundaries(s, a.seq, b.seq);
  assert.throws(() => assertCompactionBoundaries(s, a.seq, a.seq));
  assert.deepEqual(sanitizeCompactHistory([assistant, tool]), [assistant, tool]);
});
